CREATE TABLE public.card (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number INT NOT NULL,
    definition  VARCHAR(255),
    term        VARCHAR(255),
    deck_id     BIGINT,
    CONSTRAINT fk_card_deck FOREIGN KEY (deck_id) REFERENCES public.deck (id)
);